<?php

namespace AppBundle\Entity;

/**
 * CapitalCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapitalCityRepository extends \Doctrine\ORM\EntityRepository
{
}
